global using Microsoft.AspNetCore.Components;
global using Radzen;
global using RpgEditor.Helpers;
global using RpgLibrary;
global using RpgLibrary.CharacterClasses;
global using RpgLibrary.ItemClasses;
global using RpgLibrary.SkillClasses;
global using RpgLibrary.SpellClasses;
global using RpgLibrary.TalentClasses;
